#pragma once

//
// Define the various device type values.  Note that values used by Microsoft
// Corporation are in the range 0-32767, and 32768-65535 are reserved for use
// by customers.
//
#define FILE_DEVICE_REGFILTER                  0x00008305

#define REGFILTER_HOOK                         (ULONG)CTL_CODE(FILE_DEVICE_REGFILTER, 0x00, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define REGFILTER_UNHOOK                       (ULONG)CTL_CODE(FILE_DEVICE_REGFILTER, 0x01, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define REGFILTER_SET_PROTECT                  (ULONG)CTL_CODE(FILE_DEVICE_REGFILTER, 0x02, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define REGFILTER_REMOVE_PROTECT               (ULONG)CTL_CODE(FILE_DEVICE_REGFILTER, 0x03, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define REGFILTER_GET_POSITION_CONTENT         (ULONG)CTL_CODE(FILE_DEVICE_REGFILTER, 0x04, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define PROCESSFILTER_HOOK                     (ULONG)CTL_CODE(FILE_DEVICE_REGFILTER, 0x05, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define PROCESSFILTER_UNHOOK                   (ULONG)CTL_CODE(FILE_DEVICE_REGFILTER, 0x06, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define PROCESSFILTER_SET_PROTECT              (ULONG)CTL_CODE(FILE_DEVICE_REGFILTER, 0x07, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define PROCESSFILTER_REMOVE_PROTECT           (ULONG)CTL_CODE(FILE_DEVICE_REGFILTER, 0x08, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define PROCESSFILTER_GET_POSITION_CONTENT     (ULONG)CTL_CODE(FILE_DEVICE_REGFILTER, 0x09, METHOD_BUFFERED, FILE_ANY_ACCESS)


