#ifndef __KSFILTER_H_KL_2007_05_08__
#define __KSFILTER_H_KL_2007_05_08__

#pragma once

#define FSCTL_SET_PROTECT_FILE		 CTL_CODE(FILE_DEVICE_DISK_FILE_SYSTEM, 0x00, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_REMOVE_PROTECT_FILE    CTL_CODE(FILE_DEVICE_DISK_FILE_SYSTEM, 0x01, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_GET_POSITION_FILE      CTL_CODE(FILE_DEVICE_DISK_FILE_SYSTEM, 0x02, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_SAVE_CONFIG_FILE       CTL_CODE(FILE_DEVICE_DISK_FILE_SYSTEM, 0x03, METHOD_BUFFERED, FILE_ANY_ACCESS)


#endif //__KSFILTER_H_KL_2007_05_08__