// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "ctrvideo.h"

/////////////////////////////////////////////////////////////////////////////
// CVideoCtr

IMPLEMENT_DYNCREATE(CVideoCtr, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CVideoCtr properties

/////////////////////////////////////////////////////////////////////////////
// CVideoCtr operations

BOOL CVideoCtr::StartCapture()
{
	BOOL result;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CVideoCtr::StopCapture()
{
	BOOL result;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CVideoCtr::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
