// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "displayvideo.h"

/////////////////////////////////////////////////////////////////////////////
// CDisplayVideo

IMPLEMENT_DYNCREATE(CDisplayVideo, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CDisplayVideo properties

/////////////////////////////////////////////////////////////////////////////
// CDisplayVideo operations

void CDisplayVideo::Display(BSTR* lpData, long dwSize)
{
	static BYTE parms[] =
		VTS_PBSTR VTS_I4;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 lpData, dwSize);
}

void CDisplayVideo::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
