#if !defined(AFX_DISPLAYVIDEO_H__793ED88B_3AEA_4A27_9D98_AC8A9443B88A__INCLUDED_)
#define AFX_DISPLAYVIDEO_H__793ED88B_3AEA_4A27_9D98_AC8A9443B88A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDisplayVideo wrapper class

class CDisplayVideo : public CWnd
{
protected:
	DECLARE_DYNCREATE(CDisplayVideo)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xafd9ec81, 0x5ced, 0x4d82, { 0xba, 0x94, 0x81, 0x90, 0x86, 0xc4, 0xd5, 0x69 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void Display(BSTR* lpData, long dwSize);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DISPLAYVIDEO_H__793ED88B_3AEA_4A27_9D98_AC8A9443B88A__INCLUDED_)
